# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfPoMHkvCFfEoy68DKLPQ9Gycdymsm9o
"""

import streamlit as st
import pickle

# Load model
with open("sentiment_model.pkl", "rb") as f:
    model_package = pickle.load(f)

vectorizer = model_package["vectorizer"]
model = model_package["model"]

st.set_page_config(
    page_title="Analisis Sentimen",
    page_icon="😊"
)

st.title("Analisis Sentimen Review")

text = st.text_area(
    "Masukkan Review"
)

if st.button("Prediksi"):

    if text.strip() == "":
        st.warning("Masukkan teks terlebih dahulu")

    else:

        text_vec = vectorizer.transform([text])

        pred = model.predict(text_vec)[0]

        if pred == 1:
            st.success("😊 Sentimen Positif")
        else:
            st.error("😞 Sentimen Negatif")

